#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$root"

baseline=.github/upstream-watch-baseline.json
repository=$(jq -r '.repository' "$baseline")
pinned_release=$(jq -r '.release' "$baseline")
pinned_commit=$(jq -r '.commit' "$baseline")
baseline_advisories=$(jq -r '.advisories[]' "$baseline" | sort)

latest_release=$(gh api "repos/$repository/releases/latest" --jq '.tag_name')
default_branch=$(gh api "repos/$repository" --jq '.default_branch')
head_commit=$(gh api "repos/$repository/commits/$default_branch" --jq '.sha')
compare=$(gh api "repos/$repository/compare/$pinned_commit...$head_commit")
ahead_by=$(printf '%s' "$compare" | jq -r '.ahead_by')
changed_tests=$(printf '%s' "$compare" | jq -r '[.files[]?.filename | select(startswith("test/") or startswith("tests/") or contains("test"))] | unique | join(", ")')

if advisories_json=$(gh api "repos/$repository/security-advisories?state=published&per_page=100" 2>/dev/null); then
	current_advisories=$(printf '%s' "$advisories_json" | jq -r '.[].ghsa_id' | sort)
else
	echo 'warning: security-advisories API was unavailable; advisory review is required' >&2
	current_advisories='API_UNAVAILABLE'
fi

release_changed=false
test_changed=false
advisories_changed=false
[ "$latest_release" = "$pinned_release" ] || release_changed=true
if [ -n "$changed_tests" ]; then
	test_changed=true
fi
[ "$current_advisories" = "$baseline_advisories" ] || advisories_changed=true

if [ "$release_changed" = false ] && [ "$test_changed" = false ] && [ "$advisories_changed" = false ]; then
	echo "upstream $repository matches the reviewed baseline"
	rm -f .github/upstream-review.md
	exit 0
fi

{
	echo '# Upstream JSONata compatibility review'
	echo
	echo 'This file is generated by the scheduled upstream-watch workflow. It is a review request, not an automatic compatibility-target update.'
	echo
	echo "- Repository: \`$repository\`"
	echo "- Reviewed release: \`$pinned_release\`"
	echo "- Reviewed commit: \`$pinned_commit\`"
	echo "- Latest release: \`$latest_release\`"
	echo "- Default branch head: \`$head_commit\` (\`$ahead_by\` commits ahead)"
	echo "- Test-related changed files: \`${changed_tests:-none reported by the compare API}\`"
	echo "- Release changed: \`$release_changed\`"
	echo "- Tests changed: \`$test_changed\`"
	echo "- Advisories changed: \`$advisories_changed\`"
	echo "- Current advisory IDs: \`${current_advisories:-none}\`"
	echo
	echo 'Before changing the compatibility target, review upstream release notes, tests, advisories, conformance output, and license notices. Update the baseline and generated reports only in that reviewed change.'
} > .github/upstream-review.md

echo 'upstream changes require an explicit compatibility review'
